### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

Example
This is just an example in case you need it.

<img width="860" alt="68747470733a2f2f6c667a2d7374617469632e73332d75732d776573742d312e616d617a6f6e6177732e636f6d2f67726170686963732f64656d6f732f64726976696e672d67616d652f757365722d63616e2d7365652d74686569722d6361722e706e67" src="https://user-images.githubusercontent.com/80491609/126692702-12de7a85-9555-4fc7-b876-be1c728e7727.png">

## ✅ Task List

- [x] create HTML, CSS, and JavaScript files
- [x] Link all the files together in the HTML
- [x] Create the HTML foundation
- [x] Style the feature with CSS
- [x] Input the car using an img tag
- [x] Delete any comments
- [x] Get rid of any classes that aren't doing anything
- [x] Make sure code runs with no bugs
- [x] Open in incognito and make sure it still runs without any bugs
