### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

Example
This is just an example in case you need it.
![gif](https://user-images.githubusercontent.com/80491609/126701322-bd2c0414-ce26-4f3a-8446-5d607a97d655.gif)

## ✅ Task List

- [x] Query the car
- [x] Add an event listener to listen for keydown events to turn the car
- [x] Add CSS classes that will rotate the car according to which directional arrow key was pressed
- [x] Write the code for the the callback function in the event listener to rotate the car when a key is pressed
