### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by daniel-sj-hong** [daniel-sj-hong/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

Example
This is just an example in case you need it.

![gif](https://user-images.githubusercontent.com/80491609/126714550-b456c8da-7c02-45d4-be02-655ea64961c9.gif)

- [x] Create the data model
- [x] Make the car absolutely positioned
- [x] Write a function that listens for the spacebar
- [x] If the keypress is a spacebar, then move the car
